overrides:
  - files:
    - "src/**/*.ts"
extends:
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
rules:
  prefer-const: error
  prefer-destructuring: error
  indent:
    - error
    - 2
  camelcase:
    - warn
    - properties: never
      allow: [^vfunc_, ^on_, _instance_init]
  object-curly-spacing:
    - error
    - always
