rules:
  prefer-const: error
  prefer-destructuring: error
  indent:
    - error
    - 2
  camelcase:
    - warn
    - properties: never
      allow: [^vfunc_, ^on_, _instance_init]
  object-curly-spacing:
    - error
    - always
